#theme = ""

[editor]
line-number = "absolute"
lsp.display-inlay-hints = false
popup-border = "all"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "version-control"]
separator = "│"

[keys.normal]
C-t = ":sh tree -L 8 -I '__pycache__'"
esc = ["collapse_selection", "keep_primary_selection"]
