" Vimplug configurations and plug

call plug#begin()

Plug 'jiangmiao/auto-pairs'
Plug 'w0rp/ale'
Plug 'valloric/youcompleteme'
Plug 'itchyny/lightline.vim'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'scrooloose/nerdtree'
Plug 'bagrat/vim-buffet'
Plug 'ryanoasis/vim-devicons'

call plug#end()


" Vim default configurations

if has("syntax")
	syntax on
endif

set ai
set sm
set tabstop=4
set softtabstop=4
set shiftwidth=4

set nu

set hls ic scs is

set noswapfile
set nobackup
set nowritebackup

set whichwrap+=<,>,[,]

set laststatus=2

set expandtab

" Definitions of plugins

let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1

let g:lightline = {
      \ 'colorscheme': 'darcula',
      \ }

" Macros

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>


