" Vimplug configurations and plug

call plug#begin()

Plug 'jiangmiao/auto-pairs'
Plug 'w0rp/ale'
Plug 'itchyny/lightline.vim'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'scrooloose/nerdtree'
Plug 'bagrat/vim-buffet'
Plug 'ryanoasis/vim-devicons'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

" Vim default configurations

if has("syntax")
	syntax on
endif

set ai
set sm
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set smartindent
set nu
set hls ic scs is
set noswapfile
set nobackup
set nowritebackup
set whichwrap+=<,>,[,]
set laststatus=2
set expandtab
set splitright
set splitbelow
set mouse=a

" Definitions of plugins

let g:deoplete#enable_at_startup = 1

let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1

let g:lightline = {
      \ 'colorscheme': 'darcula',
      \ }

let g:ale_linters = {
\}

let g:ale_fixers = {
\   '*': ['trim_whitespace'],
\}

let g:ale_fix_on_save = 1

" Macros

nmap <leader>n :NERDTreeFocus<CR>
nmap <C-n> :NERDTree<CR>
nmap <C-t> :NERDTreeToggle<CR>
nmap <C-f> :NERDTreeFind<CR>

" Create splits
nmap th :split<CR>
nmap tv :vsplit<CR>

