[colors]

[colors.primary]
background = "#2b292d"
foreground = "#fecdb2"

[colors.cursor]
cursor = "#fecdb2"

[colors.selection]
text = "CellForeground"
background = "#4d424b"

[colors.normal]
black = "#1f1e20"
red = "#c05862"
green = "#b1b695"
yellow = "#f5d76e"
blue = "#ffa07a"
magenta = "#f6b6c9"
cyan = "#bfbfcf"
white = "#f5f5f5"

[colors.bright]
black = "#2b292d"
red = "#e06b75"
green = "#9f9f7c"
yellow = "#fff27a"
blue = "#e88c6f"
magenta = "#ffb9cc"
cyan = "#d1d1e0"
white = "#ffffff"
