require("core.plugins_config.nvim_tree")
require("core.plugins_config.gruvbox")
require("core.plugins_config.mason")
require("core.plugins_config.gitsigns")
require("core.plugins_config.ibl")
require("core.plugins_config.autopairs")
require("core.plugins_config.completions")
require("core.plugins_config.lsp_config")
require("core.plugins_config.treesitter")
require("core.plugins_config.autotag")
require("core.plugins_config.lualine")
require("core.plugins_config.telescope")

